#!/usr/bin/env python3

"""
AWS SM key management tool
"""

import click
from tabulate import tabulate
from src.common.logger import logger
from src.helpers.aws import SecretsManager

sm = SecretsManager()

@click.command()
def list():
    logger.debug("list command invocated")
    res = sm.keys()
    data = []
    for k in res:
        data.append([k["Name"], str(k["CreatedDate"]), str(k["LastChangedDate"])])
    print(tabulate(data, headers=["Name", "Created", "Updated"]))

@click.command()
@click.argument("name")
def get(name):
    try:
        res = sm[name]
        print(res["SecretString"])
    except KeyError:
        logger.error("AWS SM secret not found: %s"%name)

@click.command()
@click.argument("name")
def drop(name):
    try:
        del sm[name]
    except KeyError:
        logger.error("AWS SM secret not found: %s"%name)

@click.command()
@click.argument("name")
@click.argument("secret")
@click.option("--description", default="", help="Description of the secret")
def create(name, secret, description):
    sm.create_or_change_secret(name, secret, description)

@click.group()
def main():
    logger.debug("AWS Secrets management tool")


main.add_command(list)
main.add_command(create)
main.add_command(get)
main.add_command(drop)

if __name__ == '__main__':
    main()
